/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./components/aboutTab.vue')['default']
    FilesTab: typeof import('./components/filesTab.vue')['default']
    FolderPicker: typeof import('./components/folderPicker.vue')['default']
    PlayerTab: typeof import('./components/playerTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
